development:
  adapter: mysql
  database: battery-check
  username: root
  password: matthews

test:
  adapter: mysql
  database: battery-check-test
  username: root
  password: matthews

production:
  adapter: mysql
  database: battery-check
  username: root
  password: matthews
