development:
  adapter: mysql
  database: fsn-tools
  username: root
  password: matthews

test:
  adapter: mysql
  database: fsn-tools-test
  username: root
  password: matthews

production:
  adapter: mysql
  database: fsn-tools
  username: root
  password: matthews
